In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

data = pd.read_csv('../../../data/science.csv')

X = data[['US science spending']]
y = data['Suicides']

x_train, x_test, y_train, y_test = train_test_split(X, y)

model = LinearRegression()
model.fit(x_train, y_train)

targets = model.predict(x_train)

train_score = model.score(x_train, y_train)
test_score = model.score(x_test, y_test)

print('Training Score:', train_score)
print('Testing Score:', test_score)

x_test

Training Score: 0.9864525016248761
Testing Score: 0.9657850712914227

    US science spending
10                29449
4                 20831
2                 19753

1. load 'iris_data.csv' into a dataframe
2. get unique labels (Species column)
3. plot with a scatter plot each iris flower sample colored by label (3 different colors)
4. use: MeanShift and estimate_bandwidth from sklearn.cluster to first estimate bandwidth and then get the clusters (HINT: estimate_bandwidth() takes an argument: quantile set it to 0.2 for best result
5. print out labels, cluster centers and number of clusters (as returned from the MeanShift function
6. create a new scatter plot where each flower is colored according to cluster label
7. add a dot for the cluster centers
8. Compare the 2 plots (colored by actual labels vs. colored by cluster label)

In [28]:
import pandas as pd
from sklearn.cluster import MeanShift, estimate_bandwidth

data = pd.read_csv('../../../data/iris_data.csv')

#labels, cluster_centers, n_clusters = mean_shift(data)

data

    Sepal length Sepal width Petal length Petal width       Species
0           5,10        3,50         1,40        0,20     I. setosa
1           4,90        3,00         1,40        0,20     I. setosa
2           4,70        3,20         1,30        0,20     I. setosa
3           4,60        3,10         1,50        0,20     I. setosa
4           5,00        3,60         1,40        0,20     I. setosa
..           ...         ...          ...         ...           ...
145         6,70        3,00         5,20        2,30  I. virginica
146         6,30        2,50         5,00        1,90  I. virginica
147         6,50        3,00         5,20        2,00  I. virginica
148         6,20        3,40         5,40        2,30  I. virginica
149         5,90        3,00         5,10        1,80  I. virginica

[150 rows x 5 columns]